### PR TITLE
Change key vault to track2

### PR DESCRIPTION
**Pull request by Luyunmt**
Change key vault to track2.
@jongio for notification.

### CODE REVIEW

**Comment by v-xuto** [comment]
@jongio - Can you help ping the corresponding person to review this PR?

**Comment by v-xuto** [comment]
@jongio We don't have permission for this PR, because Luyunmt has resigned and this PR was missed to give us permission. Could you please help close it? We will create a new PR to replace it.

**Comment by v-xuto** [comment]
@jongio We don't have permission for this PR, because Luyunmt has resigned and this PR was missed to give us permission. Could you please help close it? We will create a new PR to replace it.

**Comment by Tianyun-G** [comment]
Create a new PR https://github.com/Azure-Samples/cosmosdb-dotnet-create-documentdb-and-configure-for-high-availability/pull/3 to replace this.

**Pull request closed without merging**
